# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SEMG_Assistant_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1042, 858)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.label_title = QtWidgets.QLabel(Form)
        self.label_title.setGeometry(QtCore.QRect(310, 0, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.label_remind = QtWidgets.QLabel(Form)
        self.label_remind.setGeometry(QtCore.QRect(300, 40, 511, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 207, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_remind.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_remind.setFont(font)
        self.label_remind.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_remind.setStyleSheet("background-color: rgb(255, 207, 253);")
        self.label_remind.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_remind.setObjectName("label_remind")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 70, 231, 781))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_semg_0 = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_semg_0.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_semg_0.setFont(font)
        self.label_semg_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_semg_0.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.label_semg_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_semg_0.setObjectName("label_semg_0")
        self.verticalLayout.addWidget(self.label_semg_0)
        self.label_semg_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_semg_1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_semg_1.setFont(font)
        self.label_semg_1.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.label_semg_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_semg_1.setObjectName("label_semg_1")
        self.verticalLayout.addWidget(self.label_semg_1)
        self.label_semg_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_semg_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_semg_2.setFont(font)
        self.label_semg_2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_semg_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_semg_2.setObjectName("label_semg_2")
        self.verticalLayout.addWidget(self.label_semg_2)
        self.label_semg_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_semg_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.label_semg_3.setFont(font)
        self.label_semg_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label_semg_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_semg_3.setObjectName("label_semg_3")
        self.verticalLayout.addWidget(self.label_semg_3)
        self.label_time_0 = QtWidgets.QLabel(Form)
        self.label_time_0.setGeometry(QtCore.QRect(570, 80, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_time_0.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_time_0.setFont(font)
        self.label_time_0.setStyleSheet("")
        self.label_time_0.setObjectName("label_time_0")
        self.label_fre_0 = QtWidgets.QLabel(Form)
        self.label_fre_0.setGeometry(QtCore.QRect(571, 171, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_fre_0.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_fre_0.setFont(font)
        self.label_fre_0.setStyleSheet("")
        self.label_fre_0.setObjectName("label_fre_0")
        self.label_time_1 = QtWidgets.QLabel(Form)
        self.label_time_1.setGeometry(QtCore.QRect(570, 270, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_time_1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_time_1.setFont(font)
        self.label_time_1.setStyleSheet("")
        self.label_time_1.setObjectName("label_time_1")
        self.label_time_2 = QtWidgets.QLabel(Form)
        self.label_time_2.setGeometry(QtCore.QRect(570, 470, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_time_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_time_2.setFont(font)
        self.label_time_2.setStyleSheet("")
        self.label_time_2.setObjectName("label_time_2")
        self.label_time_3 = QtWidgets.QLabel(Form)
        self.label_time_3.setGeometry(QtCore.QRect(570, 660, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_time_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_time_3.setFont(font)
        self.label_time_3.setStyleSheet("")
        self.label_time_3.setObjectName("label_time_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 110, 811, 28))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_time_max_0 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_max_0.setFont(font)
        self.label_time_max_0.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_time_max_0.setObjectName("label_time_max_0")
        self.horizontalLayout.addWidget(self.label_time_max_0)
        self.label_time_min_0 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_min_0.setFont(font)
        self.label_time_min_0.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_time_min_0.setObjectName("label_time_min_0")
        self.horizontalLayout.addWidget(self.label_time_min_0)
        self.label_time_mean_0 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_mean_0.setFont(font)
        self.label_time_mean_0.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_time_mean_0.setObjectName("label_time_mean_0")
        self.horizontalLayout.addWidget(self.label_time_mean_0)
        self.label_time_var_0 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_var_0.setFont(font)
        self.label_time_var_0.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_time_var_0.setObjectName("label_time_var_0")
        self.horizontalLayout.addWidget(self.label_time_var_0)
        self.label_time_rms_0 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_rms_0.setFont(font)
        self.label_time_rms_0.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_time_rms_0.setObjectName("label_time_rms_0")
        self.horizontalLayout.addWidget(self.label_time_rms_0)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 300, 811, 28))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_time_max_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_max_1.setFont(font)
        self.label_time_max_1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_time_max_1.setObjectName("label_time_max_1")
        self.horizontalLayout_2.addWidget(self.label_time_max_1)
        self.label_time_min_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_min_1.setFont(font)
        self.label_time_min_1.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_time_min_1.setObjectName("label_time_min_1")
        self.horizontalLayout_2.addWidget(self.label_time_min_1)
        self.label_time_mean_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_mean_1.setFont(font)
        self.label_time_mean_1.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_time_mean_1.setObjectName("label_time_mean_1")
        self.horizontalLayout_2.addWidget(self.label_time_mean_1)
        self.label_time_var_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_var_1.setFont(font)
        self.label_time_var_1.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_time_var_1.setObjectName("label_time_var_1")
        self.horizontalLayout_2.addWidget(self.label_time_var_1)
        self.label_time_rms_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_rms_1.setFont(font)
        self.label_time_rms_1.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_time_rms_1.setObjectName("label_time_rms_1")
        self.horizontalLayout_2.addWidget(self.label_time_rms_1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(230, 500, 811, 28))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_time_max_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_max_2.setFont(font)
        self.label_time_max_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_time_max_2.setObjectName("label_time_max_2")
        self.horizontalLayout_3.addWidget(self.label_time_max_2)
        self.label_time_min_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_min_2.setFont(font)
        self.label_time_min_2.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_time_min_2.setObjectName("label_time_min_2")
        self.horizontalLayout_3.addWidget(self.label_time_min_2)
        self.label_time_mean_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_mean_2.setFont(font)
        self.label_time_mean_2.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_time_mean_2.setObjectName("label_time_mean_2")
        self.horizontalLayout_3.addWidget(self.label_time_mean_2)
        self.label_time_var_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_var_2.setFont(font)
        self.label_time_var_2.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_time_var_2.setObjectName("label_time_var_2")
        self.horizontalLayout_3.addWidget(self.label_time_var_2)
        self.label_time_rms_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_rms_2.setFont(font)
        self.label_time_rms_2.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_time_rms_2.setObjectName("label_time_rms_2")
        self.horizontalLayout_3.addWidget(self.label_time_rms_2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(230, 690, 811, 28))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_time_max_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_max_3.setFont(font)
        self.label_time_max_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_time_max_3.setObjectName("label_time_max_3")
        self.horizontalLayout_4.addWidget(self.label_time_max_3)
        self.label_time_min_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_min_3.setFont(font)
        self.label_time_min_3.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_time_min_3.setObjectName("label_time_min_3")
        self.horizontalLayout_4.addWidget(self.label_time_min_3)
        self.label_time_mean_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_mean_3.setFont(font)
        self.label_time_mean_3.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_time_mean_3.setObjectName("label_time_mean_3")
        self.horizontalLayout_4.addWidget(self.label_time_mean_3)
        self.label_time_var_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_var_3.setFont(font)
        self.label_time_var_3.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_time_var_3.setObjectName("label_time_var_3")
        self.horizontalLayout_4.addWidget(self.label_time_var_3)
        self.label_time_rms_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time_rms_3.setFont(font)
        self.label_time_rms_3.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_time_rms_3.setObjectName("label_time_rms_3")
        self.horizontalLayout_4.addWidget(self.label_time_rms_3)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(230, 200, 811, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_fre_med_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_med_0.setFont(font)
        self.label_fre_med_0.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_fre_med_0.setObjectName("label_fre_med_0")
        self.horizontalLayout_5.addWidget(self.label_fre_med_0)
        self.label_fre_mean_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_mean_0.setFont(font)
        self.label_fre_mean_0.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_fre_mean_0.setObjectName("label_fre_mean_0")
        self.horizontalLayout_5.addWidget(self.label_fre_mean_0)
        self.label_fre_cog_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_cog_0.setFont(font)
        self.label_fre_cog_0.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_fre_cog_0.setObjectName("label_fre_cog_0")
        self.horizontalLayout_5.addWidget(self.label_fre_cog_0)
        self.label_fre_mse_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_mse_0.setFont(font)
        self.label_fre_mse_0.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_fre_mse_0.setObjectName("label_fre_mse_0")
        self.horizontalLayout_5.addWidget(self.label_fre_mse_0)
        self.label_fre_var_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_var_0.setFont(font)
        self.label_fre_var_0.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_fre_var_0.setObjectName("label_fre_var_0")
        self.horizontalLayout_5.addWidget(self.label_fre_var_0)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(229, 389, 811, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_fre_med_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_med_1.setFont(font)
        self.label_fre_med_1.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_fre_med_1.setObjectName("label_fre_med_1")
        self.horizontalLayout_6.addWidget(self.label_fre_med_1)
        self.label_fre_mean_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_mean_1.setFont(font)
        self.label_fre_mean_1.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_fre_mean_1.setObjectName("label_fre_mean_1")
        self.horizontalLayout_6.addWidget(self.label_fre_mean_1)
        self.label_fre_cog_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_cog_1.setFont(font)
        self.label_fre_cog_1.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_fre_cog_1.setObjectName("label_fre_cog_1")
        self.horizontalLayout_6.addWidget(self.label_fre_cog_1)
        self.label_fre_mse_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_mse_1.setFont(font)
        self.label_fre_mse_1.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_fre_mse_1.setObjectName("label_fre_mse_1")
        self.horizontalLayout_6.addWidget(self.label_fre_mse_1)
        self.label_fre_var_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_var_1.setFont(font)
        self.label_fre_var_1.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_fre_var_1.setObjectName("label_fre_var_1")
        self.horizontalLayout_6.addWidget(self.label_fre_var_1)
        self.label_fre_1 = QtWidgets.QLabel(Form)
        self.label_fre_1.setGeometry(QtCore.QRect(570, 360, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_fre_1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_fre_1.setFont(font)
        self.label_fre_1.setStyleSheet("")
        self.label_fre_1.setObjectName("label_fre_1")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(230, 590, 811, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_fre_med_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_med_2.setFont(font)
        self.label_fre_med_2.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_fre_med_2.setObjectName("label_fre_med_2")
        self.horizontalLayout_7.addWidget(self.label_fre_med_2)
        self.label_fre_mean_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_mean_2.setFont(font)
        self.label_fre_mean_2.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_fre_mean_2.setObjectName("label_fre_mean_2")
        self.horizontalLayout_7.addWidget(self.label_fre_mean_2)
        self.label_fre_cog_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_cog_2.setFont(font)
        self.label_fre_cog_2.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_fre_cog_2.setObjectName("label_fre_cog_2")
        self.horizontalLayout_7.addWidget(self.label_fre_cog_2)
        self.label_fre_mse_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_mse_2.setFont(font)
        self.label_fre_mse_2.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_fre_mse_2.setObjectName("label_fre_mse_2")
        self.horizontalLayout_7.addWidget(self.label_fre_mse_2)
        self.label_fre_var_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_var_2.setFont(font)
        self.label_fre_var_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_fre_var_2.setObjectName("label_fre_var_2")
        self.horizontalLayout_7.addWidget(self.label_fre_var_2)
        self.label_fre_2 = QtWidgets.QLabel(Form)
        self.label_fre_2.setGeometry(QtCore.QRect(571, 561, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_fre_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_fre_2.setFont(font)
        self.label_fre_2.setStyleSheet("")
        self.label_fre_2.setObjectName("label_fre_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(229, 779, 811, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_fre_med_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_med_3.setFont(font)
        self.label_fre_med_3.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.label_fre_med_3.setObjectName("label_fre_med_3")
        self.horizontalLayout_8.addWidget(self.label_fre_med_3)
        self.label_fre_mean_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_mean_3.setFont(font)
        self.label_fre_mean_3.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.label_fre_mean_3.setObjectName("label_fre_mean_3")
        self.horizontalLayout_8.addWidget(self.label_fre_mean_3)
        self.label_fre_cog_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_cog_3.setFont(font)
        self.label_fre_cog_3.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.label_fre_cog_3.setObjectName("label_fre_cog_3")
        self.horizontalLayout_8.addWidget(self.label_fre_cog_3)
        self.label_fre_mse_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fre_mse_3.setFont(font)
        self.label_fre_mse_3.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"background-color: rgb(170, 255, 127);")
        self.label_fre_mse_3.setObjectName("label_fre_mse_3")
        self.horizontalLayout_8.addWidget(self.label_fre_mse_3)
        self.label_fre_var_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fre_var_3.setFont(font)
        self.label_fre_var_3.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_fre_var_3.setObjectName("label_fre_var_3")
        self.horizontalLayout_8.addWidget(self.label_fre_var_3)
        self.label_fre_3 = QtWidgets.QLabel(Form)
        self.label_fre_3.setGeometry(QtCore.QRect(570, 750, 151, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 254, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_fre_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        font.setUnderline(False)
        self.label_fre_3.setFont(font)
        self.label_fre_3.setStyleSheet("")
        self.label_fre_3.setObjectName("label_fre_3")
        self.var_label_time_max_0 = QtWidgets.QLabel(Form)
        self.var_label_time_max_0.setGeometry(QtCore.QRect(230, 140, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_max_0.setFont(font)
        self.var_label_time_max_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_max_0.setObjectName("var_label_time_max_0")
        self.var_label_time_min_0 = QtWidgets.QLabel(Form)
        self.var_label_time_min_0.setGeometry(QtCore.QRect(400, 140, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_min_0.setFont(font)
        self.var_label_time_min_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_min_0.setObjectName("var_label_time_min_0")
        self.var_label_time_mean_0 = QtWidgets.QLabel(Form)
        self.var_label_time_mean_0.setGeometry(QtCore.QRect(560, 140, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_mean_0.setFont(font)
        self.var_label_time_mean_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_mean_0.setObjectName("var_label_time_mean_0")
        self.var_label_time_var_0 = QtWidgets.QLabel(Form)
        self.var_label_time_var_0.setGeometry(QtCore.QRect(730, 140, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_var_0.setFont(font)
        self.var_label_time_var_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_var_0.setObjectName("var_label_time_var_0")
        self.var_label_time_rms_0 = QtWidgets.QLabel(Form)
        self.var_label_time_rms_0.setGeometry(QtCore.QRect(900, 140, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_rms_0.setFont(font)
        self.var_label_time_rms_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_rms_0.setObjectName("var_label_time_rms_0")
        self.var_label_time_max_1 = QtWidgets.QLabel(Form)
        self.var_label_time_max_1.setGeometry(QtCore.QRect(230, 330, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_max_1.setFont(font)
        self.var_label_time_max_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_max_1.setObjectName("var_label_time_max_1")
        self.var_label_time_min_1 = QtWidgets.QLabel(Form)
        self.var_label_time_min_1.setGeometry(QtCore.QRect(400, 330, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_min_1.setFont(font)
        self.var_label_time_min_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_min_1.setObjectName("var_label_time_min_1")
        self.var_label_time_mean_1 = QtWidgets.QLabel(Form)
        self.var_label_time_mean_1.setGeometry(QtCore.QRect(560, 330, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_mean_1.setFont(font)
        self.var_label_time_mean_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_mean_1.setObjectName("var_label_time_mean_1")
        self.var_label_time_var_1 = QtWidgets.QLabel(Form)
        self.var_label_time_var_1.setGeometry(QtCore.QRect(730, 330, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_var_1.setFont(font)
        self.var_label_time_var_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_var_1.setObjectName("var_label_time_var_1")
        self.var_label_time_rms_1 = QtWidgets.QLabel(Form)
        self.var_label_time_rms_1.setGeometry(QtCore.QRect(900, 330, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_rms_1.setFont(font)
        self.var_label_time_rms_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_rms_1.setObjectName("var_label_time_rms_1")
        self.var_label_time_max_2 = QtWidgets.QLabel(Form)
        self.var_label_time_max_2.setGeometry(QtCore.QRect(230, 530, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_max_2.setFont(font)
        self.var_label_time_max_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_max_2.setObjectName("var_label_time_max_2")
        self.var_label_time_min_2 = QtWidgets.QLabel(Form)
        self.var_label_time_min_2.setGeometry(QtCore.QRect(400, 530, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_min_2.setFont(font)
        self.var_label_time_min_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_min_2.setObjectName("var_label_time_min_2")
        self.var_label_time_mean_2 = QtWidgets.QLabel(Form)
        self.var_label_time_mean_2.setGeometry(QtCore.QRect(560, 530, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_mean_2.setFont(font)
        self.var_label_time_mean_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_mean_2.setObjectName("var_label_time_mean_2")
        self.var_label_time_var_2 = QtWidgets.QLabel(Form)
        self.var_label_time_var_2.setGeometry(QtCore.QRect(730, 530, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_var_2.setFont(font)
        self.var_label_time_var_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_var_2.setObjectName("var_label_time_var_2")
        self.var_label_time_rms_2 = QtWidgets.QLabel(Form)
        self.var_label_time_rms_2.setGeometry(QtCore.QRect(900, 530, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_rms_2.setFont(font)
        self.var_label_time_rms_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_rms_2.setObjectName("var_label_time_rms_2")
        self.var_label_time_max_3 = QtWidgets.QLabel(Form)
        self.var_label_time_max_3.setGeometry(QtCore.QRect(230, 720, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_max_3.setFont(font)
        self.var_label_time_max_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_max_3.setObjectName("var_label_time_max_3")
        self.var_label_time_min_3 = QtWidgets.QLabel(Form)
        self.var_label_time_min_3.setGeometry(QtCore.QRect(400, 720, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_min_3.setFont(font)
        self.var_label_time_min_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_min_3.setObjectName("var_label_time_min_3")
        self.var_label_time_mean_3 = QtWidgets.QLabel(Form)
        self.var_label_time_mean_3.setGeometry(QtCore.QRect(560, 720, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_mean_3.setFont(font)
        self.var_label_time_mean_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_mean_3.setObjectName("var_label_time_mean_3")
        self.var_label_time_var_3 = QtWidgets.QLabel(Form)
        self.var_label_time_var_3.setGeometry(QtCore.QRect(730, 720, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_var_3.setFont(font)
        self.var_label_time_var_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_var_3.setObjectName("var_label_time_var_3")
        self.var_label_time_rms_3 = QtWidgets.QLabel(Form)
        self.var_label_time_rms_3.setGeometry(QtCore.QRect(900, 720, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_time_rms_3.setFont(font)
        self.var_label_time_rms_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_time_rms_3.setObjectName("var_label_time_rms_3")
        self.var_label_fre_med_0 = QtWidgets.QLabel(Form)
        self.var_label_fre_med_0.setGeometry(QtCore.QRect(230, 230, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_med_0.setFont(font)
        self.var_label_fre_med_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_med_0.setObjectName("var_label_fre_med_0")
        self.var_label_fre_mean_0 = QtWidgets.QLabel(Form)
        self.var_label_fre_mean_0.setGeometry(QtCore.QRect(400, 230, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mean_0.setFont(font)
        self.var_label_fre_mean_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mean_0.setObjectName("var_label_fre_mean_0")
        self.var_label_fre_cog_0 = QtWidgets.QLabel(Form)
        self.var_label_fre_cog_0.setGeometry(QtCore.QRect(560, 230, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_cog_0.setFont(font)
        self.var_label_fre_cog_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_cog_0.setObjectName("var_label_fre_cog_0")
        self.var_label_fre_mse_0 = QtWidgets.QLabel(Form)
        self.var_label_fre_mse_0.setGeometry(QtCore.QRect(730, 230, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mse_0.setFont(font)
        self.var_label_fre_mse_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mse_0.setObjectName("var_label_fre_mse_0")
        self.var_label_fre_var_0 = QtWidgets.QLabel(Form)
        self.var_label_fre_var_0.setGeometry(QtCore.QRect(900, 230, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_var_0.setFont(font)
        self.var_label_fre_var_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_var_0.setObjectName("var_label_fre_var_0")
        self.var_label_fre_med_1 = QtWidgets.QLabel(Form)
        self.var_label_fre_med_1.setGeometry(QtCore.QRect(230, 420, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_med_1.setFont(font)
        self.var_label_fre_med_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_med_1.setObjectName("var_label_fre_med_1")
        self.var_label_fre_med_2 = QtWidgets.QLabel(Form)
        self.var_label_fre_med_2.setGeometry(QtCore.QRect(230, 620, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_med_2.setFont(font)
        self.var_label_fre_med_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_med_2.setObjectName("var_label_fre_med_2")
        self.var_label_fre_med_3 = QtWidgets.QLabel(Form)
        self.var_label_fre_med_3.setGeometry(QtCore.QRect(230, 810, 161, 26))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_med_3.setFont(font)
        self.var_label_fre_med_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_med_3.setObjectName("var_label_fre_med_3")
        self.var_label_fre_mean_1 = QtWidgets.QLabel(Form)
        self.var_label_fre_mean_1.setGeometry(QtCore.QRect(400, 420, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mean_1.setFont(font)
        self.var_label_fre_mean_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mean_1.setObjectName("var_label_fre_mean_1")
        self.var_label_fre_mean_2 = QtWidgets.QLabel(Form)
        self.var_label_fre_mean_2.setGeometry(QtCore.QRect(400, 620, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mean_2.setFont(font)
        self.var_label_fre_mean_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mean_2.setObjectName("var_label_fre_mean_2")
        self.var_label_fre_mean_3 = QtWidgets.QLabel(Form)
        self.var_label_fre_mean_3.setGeometry(QtCore.QRect(400, 810, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mean_3.setFont(font)
        self.var_label_fre_mean_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mean_3.setObjectName("var_label_fre_mean_3")
        self.var_label_fre_cog_1 = QtWidgets.QLabel(Form)
        self.var_label_fre_cog_1.setGeometry(QtCore.QRect(560, 420, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_cog_1.setFont(font)
        self.var_label_fre_cog_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_cog_1.setObjectName("var_label_fre_cog_1")
        self.var_label_fre_cog_2 = QtWidgets.QLabel(Form)
        self.var_label_fre_cog_2.setGeometry(QtCore.QRect(560, 620, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_cog_2.setFont(font)
        self.var_label_fre_cog_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_cog_2.setObjectName("var_label_fre_cog_2")
        self.var_label_fre_cog_3 = QtWidgets.QLabel(Form)
        self.var_label_fre_cog_3.setGeometry(QtCore.QRect(560, 810, 161, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_cog_3.setFont(font)
        self.var_label_fre_cog_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_cog_3.setObjectName("var_label_fre_cog_3")
        self.var_label_fre_mse_1 = QtWidgets.QLabel(Form)
        self.var_label_fre_mse_1.setGeometry(QtCore.QRect(730, 420, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mse_1.setFont(font)
        self.var_label_fre_mse_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mse_1.setObjectName("var_label_fre_mse_1")
        self.var_label_fre_mse_2 = QtWidgets.QLabel(Form)
        self.var_label_fre_mse_2.setGeometry(QtCore.QRect(730, 620, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mse_2.setFont(font)
        self.var_label_fre_mse_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mse_2.setObjectName("var_label_fre_mse_2")
        self.var_label_fre_mse_3 = QtWidgets.QLabel(Form)
        self.var_label_fre_mse_3.setGeometry(QtCore.QRect(730, 810, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_mse_3.setFont(font)
        self.var_label_fre_mse_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_mse_3.setObjectName("var_label_fre_mse_3")
        self.var_label_fre_var_1 = QtWidgets.QLabel(Form)
        self.var_label_fre_var_1.setGeometry(QtCore.QRect(900, 420, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_var_1.setFont(font)
        self.var_label_fre_var_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_var_1.setObjectName("var_label_fre_var_1")
        self.var_label_fre_var_2 = QtWidgets.QLabel(Form)
        self.var_label_fre_var_2.setGeometry(QtCore.QRect(900, 620, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_var_2.setFont(font)
        self.var_label_fre_var_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_var_2.setObjectName("var_label_fre_var_2")
        self.var_label_fre_var_3 = QtWidgets.QLabel(Form)
        self.var_label_fre_var_3.setGeometry(QtCore.QRect(900, 810, 141, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.var_label_fre_var_3.setFont(font)
        self.var_label_fre_var_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.var_label_fre_var_3.setObjectName("var_label_fre_var_3")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 70, 811, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(230, 260, 811, 21))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(230, 450, 811, 21))
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(230, 650, 811, 21))
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(370, 650, 811, 21))
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(230, 840, 811, 21))
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.label.setStyleSheet("image: url(:/新前缀/C:/Users/lee/Pictures/QQ截图20221222013556.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 161, 71))
        self.label_2.setStyleSheet("image: url(:/ican/C:/Users/lee/Pictures/QQ截图20221026002707.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(790, 0, 121, 71))
        self.label_3.setStyleSheet("image: url(:/nuc/C:/Users/lee/Pictures/QQ截图20221222013556.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(230, 10, 71, 61))
        self.label_4.setStyleSheet("image: url(:/lc/C:/Users/lee/Pictures/QQ截图20221026002634.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(890, 0, 141, 71))
        self.label_5.setStyleSheet("image: url(:/st/C:/Users/lee/Pictures/QQ截图20221026002545.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(160, 10, 71, 51))
        self.label_6.setStyleSheet("image: url(:/lcsc/C:/Users/lee/Pictures/QQ截图20221026002642.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SEMG Assistant V1.0"))
        self.label_title.setText(_translate("Form", "四通道SEMG信号分析助手v1.0"))
        self.label_remind.setText(_translate("Form", "工训A413实验室自制软件 作者：李老色批  wx:lzs11061401"))
        self.label_semg_0.setText(_translate("Form", "SEMG信号通道0"))
        self.label_semg_1.setText(_translate("Form", "SEMG信号通道1"))
        self.label_semg_2.setText(_translate("Form", "SEMG信号通道2"))
        self.label_semg_3.setText(_translate("Form", "SEMG信号通道3"))
        self.label_time_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">时域特征</p></body></html>"))
        self.label_fre_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">功率谱特征</p></body></html>"))
        self.label_time_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">时域特征</p></body></html>"))
        self.label_time_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">时域特征</p></body></html>"))
        self.label_time_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">时域特征</p></body></html>"))
        self.label_time_max_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">最大值</p></body></html>"))
        self.label_time_min_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">最小值</p></body></html>"))
        self.label_time_mean_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">平均值</p></body></html>"))
        self.label_time_var_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">方差</p></body></html>"))
        self.label_time_rms_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">有效值</p></body></html>"))
        self.label_time_max_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">最大值</p></body></html>"))
        self.label_time_min_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">最小值</p></body></html>"))
        self.label_time_mean_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">平均值</p></body></html>"))
        self.label_time_var_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">方差</p></body></html>"))
        self.label_time_rms_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">有效值</p></body></html>"))
        self.label_time_max_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">最大值</p></body></html>"))
        self.label_time_min_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">最小值</p></body></html>"))
        self.label_time_mean_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">平均值</p></body></html>"))
        self.label_time_var_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">方差</p></body></html>"))
        self.label_time_rms_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">有效值</p></body></html>"))
        self.label_time_max_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">最大值</p></body></html>"))
        self.label_time_min_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">最小值</p></body></html>"))
        self.label_time_mean_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">平均值</p></body></html>"))
        self.label_time_var_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">方差</p></body></html>"))
        self.label_time_rms_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">有效值</p></body></html>"))
        self.label_fre_med_0.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">中值频率</span></p></body></html>"))
        self.label_fre_mean_0.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">均值频率</span></p></body></html>"))
        self.label_fre_cog_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">重心频率</p></body></html>"))
        self.label_fre_mse_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">均方频率</p></body></html>"))
        self.label_fre_var_0.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">频率方差</span></p></body></html>"))
        self.label_fre_med_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">中值频率</span></p></body></html>"))
        self.label_fre_mean_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">均值频率</span></p></body></html>"))
        self.label_fre_cog_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">重心频率</p></body></html>"))
        self.label_fre_mse_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">均方频率</p></body></html>"))
        self.label_fre_var_1.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">频率方差</span></p></body></html>"))
        self.label_fre_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">功率谱特征</p></body></html>"))
        self.label_fre_med_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">中值频率</span></p></body></html>"))
        self.label_fre_mean_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">均值频率</span></p></body></html>"))
        self.label_fre_cog_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">重心频率</p></body></html>"))
        self.label_fre_mse_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">均方频率</p></body></html>"))
        self.label_fre_var_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">频率方差</span></p></body></html>"))
        self.label_fre_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">功率谱特征</p></body></html>"))
        self.label_fre_med_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">中值频率</span></p></body></html>"))
        self.label_fre_mean_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">均值频率</span></p></body></html>"))
        self.label_fre_cog_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">重心频率</p></body></html>"))
        self.label_fre_mse_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">均方频率</p></body></html>"))
        self.label_fre_var_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">频率方差</span></p></body></html>"))
        self.label_fre_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">功率谱特征</p></body></html>"))
        self.var_label_time_max_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_min_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_mean_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_var_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_rms_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_max_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_min_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_mean_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_var_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_rms_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_max_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_min_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_mean_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_var_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_rms_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_max_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_min_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_mean_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_var_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_time_rms_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_med_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mean_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_cog_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mse_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_var_0.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_med_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_med_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_med_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mean_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mean_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mean_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_cog_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_cog_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_cog_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mse_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mse_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_mse_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_var_1.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_var_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.var_label_fre_var_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">0</p></body></html>"))
